{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "karpenter-provider-hetzner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-provider-hetzner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
